name: Generate Kakao AdBlock Filter

on:
  schedule:
    # Run every hour (only commits when changes detected)
    - cron: '0 * * * *'
  workflow_dispatch:
  push:
    paths:
      - 'scripts/**'
      - '.github/workflows/generate-filter.yml'

env:
  FILTER_FILE: 'kakao-adblock-filter.txt'

jobs:
  generate-filter:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Get current timestamp
        id: timestamp
        run: |
          echo "date=$(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_OUTPUT
          echo "short_date=$(date -u '+%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Generate Kakao AdBlock Filter from Sources
        run: |
          echo "Collecting Kakao/Daum domains from real data sources..."
          python3 scripts/collect_kakao_domains.py "${{ env.FILTER_FILE }}"

          if [ ! -f "${{ env.FILTER_FILE }}" ]; then
            echo "Error: Filter file was not generated"
            exit 1
          fi

          echo "Filter generation completed"

      - name: Validate filter syntax
        run: |
          # Basic syntax validation
          echo "Validating filter syntax..."

          # Check for proper AdGuard DNS syntax
          if grep -E '^[^!#].*[^$]$' "${{ env.FILTER_FILE }}" | grep -v '||.*\^' | grep -v '^[a-zA-Z0-9.-]*$'; then
            echo "Warning: Some lines may not follow proper AdGuard DNS syntax"
          fi

          # Count rules
          RULE_COUNT=$(grep -c '^||.*\^' "${{ env.FILTER_FILE }}" || echo "0")
          echo "Generated $RULE_COUNT blocking rules"

          # Check minimum rule count
          if [ "$RULE_COUNT" -lt 10 ]; then
            echo "Warning: Low rule count ($RULE_COUNT), expected at least 10 domains"
          fi

          # Verify file is not empty
          if [ ! -s "${{ env.FILTER_FILE }}" ]; then
            echo "Error: Filter file is empty"
            exit 1
          fi

          # Check for required header information
          if ! grep -q "Title:" "${{ env.FILTER_FILE }}"; then
            echo "Error: Filter missing required title header"
            exit 1
          fi

          echo "Filter validation completed successfully - $RULE_COUNT rules generated"

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet HEAD -- "${{ env.FILTER_FILE }}"; then
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No changes detected in filter file"
          else
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Changes detected in filter file"
            git diff --name-only HEAD -- "${{ env.FILTER_FILE }}"
          fi

      - name: Commit and push changes
        if: steps.changes.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add "${{ env.FILTER_FILE }}"
          git commit -m "chore: update Kakao AdBlock filter - ${{ steps.timestamp.outputs.date }}"
          git push

      - name: Create release asset info
        if: steps.changes.outputs.changed == 'true'
        run: |
          # Generate filter statistics
          TOTAL_RULES=$(grep -c '^||.*\^' "${{ env.FILTER_FILE }}" || echo "0")
          KAKAO_RULES=$(grep '^||.*kakao.*\^' "${{ env.FILTER_FILE }}" | wc -l || echo "0")
          DAUM_RULES=$(grep '^||.*daum.*\^' "${{ env.FILTER_FILE }}" | wc -l || echo "0")
          SOURCES=$(grep "Generated from" "${{ env.FILTER_FILE }}" | head -1 || echo "Unknown")

          echo "## Kakao AdBlock Filter Statistics" > filter-stats.md
          echo "- Total blocking rules: $TOTAL_RULES" >> filter-stats.md
          echo "- Kakao-related domains: $KAKAO_RULES" >> filter-stats.md
          echo "- Daum-related domains: $DAUM_RULES" >> filter-stats.md
          echo "- $SOURCES" >> filter-stats.md
          echo "- Last updated: ${{ steps.timestamp.outputs.date }}" >> filter-stats.md
          echo "" >> filter-stats.md
          echo "## Data Sources" >> filter-stats.md
          echo "- **List-KR**: Korean-language website filters list" >> filter-stats.md
          echo "- **YousList**: Block filter for advertisements, mainly on Korean sites" >> filter-stats.md
          echo "" >> filter-stats.md
          echo "## Usage" >> filter-stats.md
          echo "Add this URL to your AdGuard DNS custom filters:" >> filter-stats.md
          echo "\`https://raw.githubusercontent.com/${{ github.repository }}/main/${{ env.FILTER_FILE }}\`" >> filter-stats.md
          echo "" >> filter-stats.md
          echo "## Auto-Update Schedule" >> filter-stats.md
          echo "This filter is automatically updated every 6 hours to include the latest blocking rules from upstream sources." >> filter-stats.md

          cat filter-stats.md

      - name: Upload filter as artifact
        uses: actions/upload-artifact@v4
        with:
          name: kakao-adblock-filter-${{ steps.timestamp.outputs.short_date }}
          path: |
            ${{ env.FILTER_FILE }}
            filter-stats.md
          retention-days: 30